web: gunicorn dish.wsgi --chdir backend --limit-request-line 8188 --log-file -
worker: REMAP_SIGTERM=SIGQUIT celery --workdir backend --app=dish worker --loglevel=info
beat: REMAP_SIGTERM=SIGQUIT celery --workdir backend --app=dish beat -S redbeat.RedBeatScheduler --loglevel=info
